var data = [
    { name: "Skipped", value: "Skipped", drp_name: "hr_status" },
    { name: "On Hold", value: "On Hold", drp_name: "hr_status" },
    { name: "In Progress", value: "In Progress", drp_name: "hr_status" },
    { name: "Completed", value: "Completed", drp_name: "hr_status" },
    { name: "Round 1", value: "Round 1", drp_name: "interview_round" },
    { name: "Round 2", value: "Round 2", drp_name: "interview_round" },
    { name: "Round 3", value: "Round 3", drp_name: "interview_round" },
    { name: "Round 4", value: "Round 4", drp_name: "interview_round" },
    { name: "Round 5", value: "Round 5", drp_name: "interview_round" },
    { name: "Not Applicable", value: "Not Applicable", drp_name: "interview_round" },
    { name: "In Progress", value: "In Progress", drp_name: "final_status" },
    { name: "Hired", value: "Hired", drp_name: "final_status" },
    { name: "Rejected", value: "Rejected", drp_name: "final_status" },
    { name: "Email Sent", value: "Email Sent", drp_name: "final_status" },
    { name: "Joined", value: "Joined", drp_name: "final_status" },
    { name: "Irrelevant Profile", value: "Irrelevant Profile", drp_name: "final_status" },
    { name: "Location Not Matched", value: "Location Not Matched", drp_name: "final_status" },
    { name: "Salary Expectation High", value: "Salary Expectation High", drp_name: "final_status" },
    { name: "Not Appeared", value: "Not Appeared", drp_name: "final_status" },
    { name: "Declined Offer", value: "Declined Offer", drp_name: "final_status" },
    { name: "On Hold", value: "On Hold", drp_name: "final_status" },
    { name: "Not Responded", value: "Not Responded", drp_name: "final_status" },
    { name: "Candidates", value: "Candidates", drp_name: "users" },
    { name: "Admin", value: "Admin", drp_name: "users" },
    { name: "HR", value: "HR", drp_name: "users" },
    { name: "Interviewer", value: "Interviewer", drp_name: "users" },
    { name: "Sr. Data Engineer / Lead Data Engineer", value: "Sr. Data Engineer / Lead Data Engineer", drp_name: "position" },
    { name: "Lead AI Engineer", value: "Lead AI Engineer", drp_name: "position" },
    { name: "Full Stack Developer", value: "Full Stack Developer", drp_name: "position" },
    { name: "Sr. Data Scientist", value: "Sr. Data Scientist", drp_name: "position" },
    { name: "Sr. BI Developer / Lead BI Developer / BI Architect", value: "Sr. BI Developer / Lead BI Developer / BI Architect", drp_name: "position" },
    { name: "Data Engineer", value: "Data Engineer", drp_name: "position" },
    { name: "Jr. Data Engineer", value: "Jr. Data Engineer", drp_name: "position" },
    { name: "3D Content Developer", value: "3D Content Developer", drp_name: "position" },
    { name: "Automation QA Engineer", value: "Automation QA Engineer", drp_name: "position" },
    { name: "Sr. Python Django Developer", value: "Sr. Python Django Developer", drp_name: "position" },
    { name: "ReactJS Developer", value: "ReactJS Developer", drp_name: "position" },
    { name: "iOS Developer", value: "iOS Developer", drp_name: "position" },
    { name: "Python Automation Engineer", value: "Python Automation Engineer", drp_name: "position" },
    { name: "Unity Developer", value: "Unity Developer", drp_name: "position" },
];

module.exports = data;